FROM node:22-alpine AS builder

WORKDIR /app

RUN corepack enable

ENV NX_DAEMON=false

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY nx.json tsconfig.base.json tsconfig.json ./

COPY apps ./apps
COPY libs ./libs

RUN pnpm config set dangerouslyAllowAllBuilds true
RUN pnpm install --frozen-lockfile

ARG APP_NAME
RUN pnpm exec nx build $APP_NAME


FROM node:22-alpine AS runner

WORKDIR /app

RUN corepack enable

ENV NX_DAEMON=false

ARG APP_NAME
ENV APP_NAME=$APP_NAME
ENV NODE_ENV=production

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY --from=builder /app/dist ./dist

RUN pnpm config set dangerouslyAllowAllBuilds true
RUN pnpm install --prod --frozen-lockfile

CMD ["sh", "-c", "node dist/apps/$APP_NAME/main.js"]