
syntax = "proto3";

package GRPC_AUTH_SERVICE;

import "google/protobuf/empty.proto";


service AuthorizerService {
  rpc registerUser (UserPayload) returns (UserResponse);
  rpc loginUser (LoginPayload) returns (LoginResponse);
  rpc refreshToken (RefreshTokenRequest) returns (AuthTokenResponse);
  rpc forgotPassword (EmailPayload) returns (google.protobuf.Empty);
  rpc resetPassword (ResetPasswordPayload) returns (google.protobuf.Empty);
  rpc verifyEmail (TokenPayload) returns (google.protobuf.Empty);
  rpc resendEmail (EmailPayload) returns (google.protobuf.Empty);
}

message RefreshTokenRequest {
  string refreshToken = 1;
}

message AuthTokenResponse {
  string accessToken = 1;
  string refreshToken = 2;
}

message LoginPayload {
  string email = 1; 
  string password = 2;
}

message LoginResponse {
  string accessToken = 1;
  string refreshToken = 2;
}

message UserPayload {
  string email = 1;
  string password = 2;
  string firstName = 3;
  string lastName = 4;
}

message UserResponse {
  string userId = 1;
}




message EmailPayload {
  string email = 1;
}

message TokenPayload {
  string token = 1;
}

message ResetPasswordPayload {
  string token = 1;
  string password = 2;
}
